spring:
  main:
    banner-mode: off
  application:
    name: Hibernate Demo
  datasource:
      driverClassName: oracle.jdbc.OracleDriver
      name: testdb
      url: jdbc:oracle:thin:@localhost:49161:xe
      username: system
      password: oracle
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.Oracle10gDialect
      ddlAuto: update